### ISSUE TITLE
Drawing Image on Chat

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#89]
### The problem

Prompt: `Draw a cat like Louis Wain`
If this prompt is typed, bing generates an image so the bot goes into a bug and appears to be typing forever.

### Version of python

latest

### Version of EdgeGPT-Telegram-Bot

latest

### Operating system running EdgeGPT-Telegram-Bot

latest

### Running on your machine? Running on docker?

latest

**Comment by scmanjarrez** [comment]
I need logs

**Comment by scmanjarrez** [comment]
Can't replicate
![image](https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/assets/9284124/2d8a0e82-6b0f-4d64-a70a-e39392a326da)

**Comment by scmanjarrez** [comment]
Currently, image generation is handled by another library (BingImageCreator), so you have to guide the bot to do what you wanted. By default, messages without `/image` command will query Bing using EdgeGPT (which doesn't handle inline images). If it generates an exception because it doesn't expect that response, the bot will crash due to that exception.
